### ISSUE TITLE
Simulator doesn't work on logs more than 24 hours

### ISSUE THREAD

**Issue by nullasync** [njtnestor/chia-plot-simulator#8]
Hi, i did a simulator using one of my old logs from last week, where i had a drive issues and my plots creations appears to be more than 24 hours. However the simulator's durations does not calculate as real time taken for the plot creations. More details are as in the following screenshots. Hope this helps. Sorry for my bad English anyway. Thanks!
![Screenshot (1)](https://user-images.githubusercontent.com/74730093/119283456-b6d90600-bc6f-11eb-9b63-8df9a30129fd.png)
Regards.

**Comment by njtnestor** [comment]
Can you attach the log file pls?

**Comment by nullasync** [comment]
> Can you attach the log file pls?

Yes sure. 
[16052021-07-42.log](https://github.com/njtnestor/chia-plot-simulator/files/6535176/16052021-07-42.log)

**Comment by mariaalonsodev** [comment]
Thank you for reporting the bug. It is now fixed and deployed!

**Comment by nullasync** [comment]
I believe the total time was more than 35 hours. I did a retest simulator using the same logs was only shown 11:57:22 while the total durations should be shown like 35:57:22.

**Comment by njtnestor** [comment]
I've been checking the log and results.

Expected result: 
Phase times(f1-f4) = 122242.186 
Copy time = 5076.647
Total time: 35:21:58

Our result:
Total time: 35:21:58
https://www.chiaplotsimulator.com/?data=yhtd2wt2
____________________________________________________________

Can you share your result? because I cant repro this 11:57:22 with the same file that you attached

There is some calc error with times>24h that we must check.
I'll reopen this issue to check it

**Comment by nullasync** [comment]
I did a re-run on the same logs as attached, turns out the results are same as your results : 35:21:58. Must be typos when writing those comments as 33:57:22 on yesterday. However it was weird when generated logs on yesterday shows 11:57:22, also i didn't manage to save the results. Never mind, its already fixed. Great tools anyway, please keep up the good works. Helped me a lot when trying to manage my plotting task! Thanks!
Edit : today's re-run logs link https://www.chiaplotsimulator.com/?data=yzyujdzp
